<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit7460a584b27887d0efcda6b935460699
{
    public static $prefixLengthsPsr4 = array (
        'P' =>
        array (
            'PuleenoCMS\\React\\' => 17,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PuleenoCMS\\React\\' =>
        array (
            0 => __DIR__ . '/../..' . '/',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit7460a584b27887d0efcda6b935460699::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit7460a584b27887d0efcda6b935460699::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit7460a584b27887d0efcda6b935460699::$classMap;
        }, null, ClassLoader::class);
    }
}
