<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit641a766a936283e339ec019c8b3d6021
{
    public static $prefixLengthsPsr4 = array (
        'Q' => 
        array (
            'Quagga\\Extension\\React\\' => 23,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Quagga\\Extension\\React\\' => 
        array (
            0 => __DIR__ . '/../..' . '/',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit641a766a936283e339ec019c8b3d6021::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit641a766a936283e339ec019c8b3d6021::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit641a766a936283e339ec019c8b3d6021::$classMap;

        }, null, ClassLoader::class);
    }
}
